/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedCheckInRouteImport } from './routes/_authenticated/check-in'
import { Route as AuthenticatedGiroSalaRouteImport } from './routes/_authenticated/giro-sala'
import { Route as AuthenticatedHospitalRouteImport } from './routes/_authenticated/hospital'
import { Route as AuthenticatedMasterRouteImport } from './routes/_authenticated/master'
import { Route as AuthenticatedOperacionalRouteImport } from './routes/_authenticated/operacional'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AuthenticatedCheckInIndexRouteImport } from './routes/_authenticated/check-in.index'
import { Route as AuthenticatedCheckInPainelRouteImport } from './routes/_authenticated/check-in.painel'
import { Route as AuthenticatedGiroSalaIndexRouteImport } from './routes/_authenticated/giro-sala.index'
import { Route as AuthenticatedGiroSalaAdminRouteImport } from './routes/_authenticated/giro-sala.admin'
import { Route as AuthenticatedHospitalIndexRouteImport } from './routes/_authenticated/hospital.index'
import { Route as AuthenticatedHospitalAcessosRouteImport } from './routes/_authenticated/hospital.acessos'
import { Route as AuthenticatedHospitalCheckInRouteImport } from './routes/_authenticated/hospital.check-in'
import { Route as AuthenticatedHospitalEquipeRouteImport } from './routes/_authenticated/hospital.equipe'
import { Route as AuthenticatedHospitalGiroSalaRouteImport } from './routes/_authenticated/hospital.giro-sala'
import { Route as AuthenticatedHospitalSalasRouteImport } from './routes/_authenticated/hospital.salas'
import { Route as AuthenticatedMasterIndexRouteImport } from './routes/_authenticated/master.index'
import { Route as AuthenticatedMasterAuditoriaRouteImport } from './routes/_authenticated/master.auditoria'
import { Route as AuthenticatedMasterConvitesRouteImport } from './routes/_authenticated/master.convites'
import { Route as AuthenticatedMasterFeaturesRouteImport } from './routes/_authenticated/master.features'
import { Route as AuthenticatedMasterHospitaisRouteImport } from './routes/_authenticated/master.hospitais'
import { Route as AuthenticatedMasterMfaRouteImport } from './routes/_authenticated/master.mfa'
import { Route as AuthenticatedMasterPermissoesRouteImport } from './routes/_authenticated/master.permissoes'
import { Route as AuthenticatedMasterUsuariosRouteImport } from './routes/_authenticated/master.usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckInRoute = AuthenticatedCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGiroSalaRoute = AuthenticatedGiroSalaRouteImport.update({
  id: '/giro-sala',
  path: '/giro-sala',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHospitalRoute = AuthenticatedHospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterRoute = AuthenticatedMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacionalRoute =
  AuthenticatedOperacionalRouteImport.update({
    id: '/operacional',
    path: '/operacional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckInIndexRoute =
  AuthenticatedCheckInIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCheckInRoute,
  } as any)
const AuthenticatedCheckInPainelRoute =
  AuthenticatedCheckInPainelRouteImport.update({
    id: '/painel',
    path: '/painel',
    getParentRoute: () => AuthenticatedCheckInRoute,
  } as any)
const AuthenticatedGiroSalaIndexRoute =
  AuthenticatedGiroSalaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGiroSalaRoute,
  } as any)
const AuthenticatedGiroSalaAdminRoute =
  AuthenticatedGiroSalaAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedGiroSalaRoute,
  } as any)
const AuthenticatedHospitalIndexRoute =
  AuthenticatedHospitalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHospitalRoute,
  } as any)
const AuthenticatedHospitalAcessosRoute =
  AuthenticatedHospitalAcessosRouteImport.update({
    id: '/acessos',
    path: '/acessos',
    getParentRoute: () => AuthenticatedHospitalRoute,
  } as any)
const AuthenticatedHospitalCheckInRoute =
  AuthenticatedHospitalCheckInRouteImport.update({
    id: '/check-in',
    path: '/check-in',
    getParentRoute: () => AuthenticatedHospitalRoute,
  } as any)
const AuthenticatedHospitalEquipeRoute =
  AuthenticatedHospitalEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedHospitalRoute,
  } as any)
const AuthenticatedHospitalGiroSalaRoute =
  AuthenticatedHospitalGiroSalaRouteImport.update({
    id: '/giro-sala',
    path: '/giro-sala',
    getParentRoute: () => AuthenticatedHospitalRoute,
  } as any)
const AuthenticatedHospitalSalasRoute =
  AuthenticatedHospitalSalasRouteImport.update({
    id: '/salas',
    path: '/salas',
    getParentRoute: () => AuthenticatedHospitalRoute,
  } as any)
const AuthenticatedMasterIndexRoute =
  AuthenticatedMasterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterAuditoriaRoute =
  AuthenticatedMasterAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterConvitesRoute =
  AuthenticatedMasterConvitesRouteImport.update({
    id: '/convites',
    path: '/convites',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterFeaturesRoute =
  AuthenticatedMasterFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterHospitaisRoute =
  AuthenticatedMasterHospitaisRouteImport.update({
    id: '/hospitais',
    path: '/hospitais',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterMfaRoute = AuthenticatedMasterMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthenticatedMasterRoute,
} as any)
const AuthenticatedMasterPermissoesRoute =
  AuthenticatedMasterPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterUsuariosRoute =
  AuthenticatedMasterUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/app': typeof AuthenticatedAppRoute
  '/check-in': typeof AuthenticatedCheckInRouteWithChildren
  '/giro-sala': typeof AuthenticatedGiroSalaRouteWithChildren
  '/hospital': typeof AuthenticatedHospitalRouteWithChildren
  '/master': typeof AuthenticatedMasterRouteWithChildren
  '/operacional': typeof AuthenticatedOperacionalRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/check-in/painel': typeof AuthenticatedCheckInPainelRoute
  '/giro-sala/admin': typeof AuthenticatedGiroSalaAdminRoute
  '/hospital/acessos': typeof AuthenticatedHospitalAcessosRoute
  '/hospital/check-in': typeof AuthenticatedHospitalCheckInRoute
  '/hospital/equipe': typeof AuthenticatedHospitalEquipeRoute
  '/hospital/giro-sala': typeof AuthenticatedHospitalGiroSalaRoute
  '/hospital/salas': typeof AuthenticatedHospitalSalasRoute
  '/master/auditoria': typeof AuthenticatedMasterAuditoriaRoute
  '/master/convites': typeof AuthenticatedMasterConvitesRoute
  '/master/features': typeof AuthenticatedMasterFeaturesRoute
  '/master/hospitais': typeof AuthenticatedMasterHospitaisRoute
  '/master/mfa': typeof AuthenticatedMasterMfaRoute
  '/master/permissoes': typeof AuthenticatedMasterPermissoesRoute
  '/master/usuarios': typeof AuthenticatedMasterUsuariosRoute
  '/check-in/': typeof AuthenticatedCheckInIndexRoute
  '/giro-sala/': typeof AuthenticatedGiroSalaIndexRoute
  '/hospital/': typeof AuthenticatedHospitalIndexRoute
  '/master/': typeof AuthenticatedMasterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/app': typeof AuthenticatedAppRoute
  '/operacional': typeof AuthenticatedOperacionalRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/check-in/painel': typeof AuthenticatedCheckInPainelRoute
  '/giro-sala/admin': typeof AuthenticatedGiroSalaAdminRoute
  '/hospital/acessos': typeof AuthenticatedHospitalAcessosRoute
  '/hospital/check-in': typeof AuthenticatedHospitalCheckInRoute
  '/hospital/equipe': typeof AuthenticatedHospitalEquipeRoute
  '/hospital/giro-sala': typeof AuthenticatedHospitalGiroSalaRoute
  '/hospital/salas': typeof AuthenticatedHospitalSalasRoute
  '/master/auditoria': typeof AuthenticatedMasterAuditoriaRoute
  '/master/convites': typeof AuthenticatedMasterConvitesRoute
  '/master/features': typeof AuthenticatedMasterFeaturesRoute
  '/master/hospitais': typeof AuthenticatedMasterHospitaisRoute
  '/master/mfa': typeof AuthenticatedMasterMfaRoute
  '/master/permissoes': typeof AuthenticatedMasterPermissoesRoute
  '/master/usuarios': typeof AuthenticatedMasterUsuariosRoute
  '/check-in': typeof AuthenticatedCheckInIndexRoute
  '/giro-sala': typeof AuthenticatedGiroSalaIndexRoute
  '/hospital': typeof AuthenticatedHospitalIndexRoute
  '/master': typeof AuthenticatedMasterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/check-in': typeof AuthenticatedCheckInRouteWithChildren
  '/_authenticated/giro-sala': typeof AuthenticatedGiroSalaRouteWithChildren
  '/_authenticated/hospital': typeof AuthenticatedHospitalRouteWithChildren
  '/_authenticated/master': typeof AuthenticatedMasterRouteWithChildren
  '/_authenticated/operacional': typeof AuthenticatedOperacionalRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/_authenticated/check-in/painel': typeof AuthenticatedCheckInPainelRoute
  '/_authenticated/giro-sala/admin': typeof AuthenticatedGiroSalaAdminRoute
  '/_authenticated/hospital/acessos': typeof AuthenticatedHospitalAcessosRoute
  '/_authenticated/hospital/check-in': typeof AuthenticatedHospitalCheckInRoute
  '/_authenticated/hospital/equipe': typeof AuthenticatedHospitalEquipeRoute
  '/_authenticated/hospital/giro-sala': typeof AuthenticatedHospitalGiroSalaRoute
  '/_authenticated/hospital/salas': typeof AuthenticatedHospitalSalasRoute
  '/_authenticated/master/auditoria': typeof AuthenticatedMasterAuditoriaRoute
  '/_authenticated/master/convites': typeof AuthenticatedMasterConvitesRoute
  '/_authenticated/master/features': typeof AuthenticatedMasterFeaturesRoute
  '/_authenticated/master/hospitais': typeof AuthenticatedMasterHospitaisRoute
  '/_authenticated/master/mfa': typeof AuthenticatedMasterMfaRoute
  '/_authenticated/master/permissoes': typeof AuthenticatedMasterPermissoesRoute
  '/_authenticated/master/usuarios': typeof AuthenticatedMasterUsuariosRoute
  '/_authenticated/check-in/': typeof AuthenticatedCheckInIndexRoute
  '/_authenticated/giro-sala/': typeof AuthenticatedGiroSalaIndexRoute
  '/_authenticated/hospital/': typeof AuthenticatedHospitalIndexRoute
  '/_authenticated/master/': typeof AuthenticatedMasterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/app'
    | '/check-in'
    | '/giro-sala'
    | '/hospital'
    | '/master'
    | '/operacional'
    | '/convite/$token'
    | '/check-in/painel'
    | '/giro-sala/admin'
    | '/hospital/acessos'
    | '/hospital/check-in'
    | '/hospital/equipe'
    | '/hospital/giro-sala'
    | '/hospital/salas'
    | '/master/auditoria'
    | '/master/convites'
    | '/master/features'
    | '/master/hospitais'
    | '/master/mfa'
    | '/master/permissoes'
    | '/master/usuarios'
    | '/check-in/'
    | '/giro-sala/'
    | '/hospital/'
    | '/master/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/app'
    | '/operacional'
    | '/convite/$token'
    | '/check-in/painel'
    | '/giro-sala/admin'
    | '/hospital/acessos'
    | '/hospital/check-in'
    | '/hospital/equipe'
    | '/hospital/giro-sala'
    | '/hospital/salas'
    | '/master/auditoria'
    | '/master/convites'
    | '/master/features'
    | '/master/hospitais'
    | '/master/mfa'
    | '/master/permissoes'
    | '/master/usuarios'
    | '/check-in'
    | '/giro-sala'
    | '/hospital'
    | '/master'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/entrar'
    | '/_authenticated/app'
    | '/_authenticated/check-in'
    | '/_authenticated/giro-sala'
    | '/_authenticated/hospital'
    | '/_authenticated/master'
    | '/_authenticated/operacional'
    | '/convite/$token'
    | '/_authenticated/check-in/painel'
    | '/_authenticated/giro-sala/admin'
    | '/_authenticated/hospital/acessos'
    | '/_authenticated/hospital/check-in'
    | '/_authenticated/hospital/equipe'
    | '/_authenticated/hospital/giro-sala'
    | '/_authenticated/hospital/salas'
    | '/_authenticated/master/auditoria'
    | '/_authenticated/master/convites'
    | '/_authenticated/master/features'
    | '/_authenticated/master/hospitais'
    | '/_authenticated/master/mfa'
    | '/_authenticated/master/permissoes'
    | '/_authenticated/master/usuarios'
    | '/_authenticated/check-in/'
    | '/_authenticated/giro-sala/'
    | '/_authenticated/hospital/'
    | '/_authenticated/master/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in': {
      id: '/_authenticated/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthenticatedCheckInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/giro-sala': {
      id: '/_authenticated/giro-sala'
      path: '/giro-sala'
      fullPath: '/giro-sala'
      preLoaderRoute: typeof AuthenticatedGiroSalaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospital': {
      id: '/_authenticated/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof AuthenticatedHospitalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional': {
      id: '/_authenticated/operacional'
      path: '/operacional'
      fullPath: '/operacional'
      preLoaderRoute: typeof AuthenticatedOperacionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/check-in/': {
      id: '/_authenticated/check-in/'
      path: '/'
      fullPath: '/check-in/'
      preLoaderRoute: typeof AuthenticatedCheckInIndexRouteImport
      parentRoute: typeof AuthenticatedCheckInRoute
    }
    '/_authenticated/check-in/painel': {
      id: '/_authenticated/check-in/painel'
      path: '/painel'
      fullPath: '/check-in/painel'
      preLoaderRoute: typeof AuthenticatedCheckInPainelRouteImport
      parentRoute: typeof AuthenticatedCheckInRoute
    }
    '/_authenticated/giro-sala/': {
      id: '/_authenticated/giro-sala/'
      path: '/'
      fullPath: '/giro-sala/'
      preLoaderRoute: typeof AuthenticatedGiroSalaIndexRouteImport
      parentRoute: typeof AuthenticatedGiroSalaRoute
    }
    '/_authenticated/giro-sala/admin': {
      id: '/_authenticated/giro-sala/admin'
      path: '/admin'
      fullPath: '/giro-sala/admin'
      preLoaderRoute: typeof AuthenticatedGiroSalaAdminRouteImport
      parentRoute: typeof AuthenticatedGiroSalaRoute
    }
    '/_authenticated/hospital/': {
      id: '/_authenticated/hospital/'
      path: '/'
      fullPath: '/hospital/'
      preLoaderRoute: typeof AuthenticatedHospitalIndexRouteImport
      parentRoute: typeof AuthenticatedHospitalRoute
    }
    '/_authenticated/hospital/acessos': {
      id: '/_authenticated/hospital/acessos'
      path: '/acessos'
      fullPath: '/hospital/acessos'
      preLoaderRoute: typeof AuthenticatedHospitalAcessosRouteImport
      parentRoute: typeof AuthenticatedHospitalRoute
    }
    '/_authenticated/hospital/check-in': {
      id: '/_authenticated/hospital/check-in'
      path: '/check-in'
      fullPath: '/hospital/check-in'
      preLoaderRoute: typeof AuthenticatedHospitalCheckInRouteImport
      parentRoute: typeof AuthenticatedHospitalRoute
    }
    '/_authenticated/hospital/equipe': {
      id: '/_authenticated/hospital/equipe'
      path: '/equipe'
      fullPath: '/hospital/equipe'
      preLoaderRoute: typeof AuthenticatedHospitalEquipeRouteImport
      parentRoute: typeof AuthenticatedHospitalRoute
    }
    '/_authenticated/hospital/giro-sala': {
      id: '/_authenticated/hospital/giro-sala'
      path: '/giro-sala'
      fullPath: '/hospital/giro-sala'
      preLoaderRoute: typeof AuthenticatedHospitalGiroSalaRouteImport
      parentRoute: typeof AuthenticatedHospitalRoute
    }
    '/_authenticated/hospital/salas': {
      id: '/_authenticated/hospital/salas'
      path: '/salas'
      fullPath: '/hospital/salas'
      preLoaderRoute: typeof AuthenticatedHospitalSalasRouteImport
      parentRoute: typeof AuthenticatedHospitalRoute
    }
    '/_authenticated/master/': {
      id: '/_authenticated/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof AuthenticatedMasterIndexRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/auditoria': {
      id: '/_authenticated/master/auditoria'
      path: '/auditoria'
      fullPath: '/master/auditoria'
      preLoaderRoute: typeof AuthenticatedMasterAuditoriaRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/convites': {
      id: '/_authenticated/master/convites'
      path: '/convites'
      fullPath: '/master/convites'
      preLoaderRoute: typeof AuthenticatedMasterConvitesRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/features': {
      id: '/_authenticated/master/features'
      path: '/features'
      fullPath: '/master/features'
      preLoaderRoute: typeof AuthenticatedMasterFeaturesRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/hospitais': {
      id: '/_authenticated/master/hospitais'
      path: '/hospitais'
      fullPath: '/master/hospitais'
      preLoaderRoute: typeof AuthenticatedMasterHospitaisRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/mfa': {
      id: '/_authenticated/master/mfa'
      path: '/mfa'
      fullPath: '/master/mfa'
      preLoaderRoute: typeof AuthenticatedMasterMfaRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/permissoes': {
      id: '/_authenticated/master/permissoes'
      path: '/permissoes'
      fullPath: '/master/permissoes'
      preLoaderRoute: typeof AuthenticatedMasterPermissoesRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/usuarios': {
      id: '/_authenticated/master/usuarios'
      path: '/usuarios'
      fullPath: '/master/usuarios'
      preLoaderRoute: typeof AuthenticatedMasterUsuariosRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
  }
}

interface AuthenticatedCheckInRouteChildren {
  AuthenticatedCheckInPainelRoute: typeof AuthenticatedCheckInPainelRoute
  AuthenticatedCheckInIndexRoute: typeof AuthenticatedCheckInIndexRoute
}

const AuthenticatedCheckInRouteChildren: AuthenticatedCheckInRouteChildren = {
  AuthenticatedCheckInPainelRoute: AuthenticatedCheckInPainelRoute,
  AuthenticatedCheckInIndexRoute: AuthenticatedCheckInIndexRoute,
}

const AuthenticatedCheckInRouteWithChildren =
  AuthenticatedCheckInRoute._addFileChildren(AuthenticatedCheckInRouteChildren)

interface AuthenticatedGiroSalaRouteChildren {
  AuthenticatedGiroSalaAdminRoute: typeof AuthenticatedGiroSalaAdminRoute
  AuthenticatedGiroSalaIndexRoute: typeof AuthenticatedGiroSalaIndexRoute
}

const AuthenticatedGiroSalaRouteChildren: AuthenticatedGiroSalaRouteChildren = {
  AuthenticatedGiroSalaAdminRoute: AuthenticatedGiroSalaAdminRoute,
  AuthenticatedGiroSalaIndexRoute: AuthenticatedGiroSalaIndexRoute,
}

const AuthenticatedGiroSalaRouteWithChildren =
  AuthenticatedGiroSalaRoute._addFileChildren(
    AuthenticatedGiroSalaRouteChildren,
  )

interface AuthenticatedHospitalRouteChildren {
  AuthenticatedHospitalAcessosRoute: typeof AuthenticatedHospitalAcessosRoute
  AuthenticatedHospitalCheckInRoute: typeof AuthenticatedHospitalCheckInRoute
  AuthenticatedHospitalEquipeRoute: typeof AuthenticatedHospitalEquipeRoute
  AuthenticatedHospitalGiroSalaRoute: typeof AuthenticatedHospitalGiroSalaRoute
  AuthenticatedHospitalSalasRoute: typeof AuthenticatedHospitalSalasRoute
  AuthenticatedHospitalIndexRoute: typeof AuthenticatedHospitalIndexRoute
}

const AuthenticatedHospitalRouteChildren: AuthenticatedHospitalRouteChildren = {
  AuthenticatedHospitalAcessosRoute: AuthenticatedHospitalAcessosRoute,
  AuthenticatedHospitalCheckInRoute: AuthenticatedHospitalCheckInRoute,
  AuthenticatedHospitalEquipeRoute: AuthenticatedHospitalEquipeRoute,
  AuthenticatedHospitalGiroSalaRoute: AuthenticatedHospitalGiroSalaRoute,
  AuthenticatedHospitalSalasRoute: AuthenticatedHospitalSalasRoute,
  AuthenticatedHospitalIndexRoute: AuthenticatedHospitalIndexRoute,
}

const AuthenticatedHospitalRouteWithChildren =
  AuthenticatedHospitalRoute._addFileChildren(
    AuthenticatedHospitalRouteChildren,
  )

interface AuthenticatedMasterRouteChildren {
  AuthenticatedMasterAuditoriaRoute: typeof AuthenticatedMasterAuditoriaRoute
  AuthenticatedMasterConvitesRoute: typeof AuthenticatedMasterConvitesRoute
  AuthenticatedMasterFeaturesRoute: typeof AuthenticatedMasterFeaturesRoute
  AuthenticatedMasterHospitaisRoute: typeof AuthenticatedMasterHospitaisRoute
  AuthenticatedMasterMfaRoute: typeof AuthenticatedMasterMfaRoute
  AuthenticatedMasterPermissoesRoute: typeof AuthenticatedMasterPermissoesRoute
  AuthenticatedMasterUsuariosRoute: typeof AuthenticatedMasterUsuariosRoute
  AuthenticatedMasterIndexRoute: typeof AuthenticatedMasterIndexRoute
}

const AuthenticatedMasterRouteChildren: AuthenticatedMasterRouteChildren = {
  AuthenticatedMasterAuditoriaRoute: AuthenticatedMasterAuditoriaRoute,
  AuthenticatedMasterConvitesRoute: AuthenticatedMasterConvitesRoute,
  AuthenticatedMasterFeaturesRoute: AuthenticatedMasterFeaturesRoute,
  AuthenticatedMasterHospitaisRoute: AuthenticatedMasterHospitaisRoute,
  AuthenticatedMasterMfaRoute: AuthenticatedMasterMfaRoute,
  AuthenticatedMasterPermissoesRoute: AuthenticatedMasterPermissoesRoute,
  AuthenticatedMasterUsuariosRoute: AuthenticatedMasterUsuariosRoute,
  AuthenticatedMasterIndexRoute: AuthenticatedMasterIndexRoute,
}

const AuthenticatedMasterRouteWithChildren =
  AuthenticatedMasterRoute._addFileChildren(AuthenticatedMasterRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedCheckInRoute: typeof AuthenticatedCheckInRouteWithChildren
  AuthenticatedGiroSalaRoute: typeof AuthenticatedGiroSalaRouteWithChildren
  AuthenticatedHospitalRoute: typeof AuthenticatedHospitalRouteWithChildren
  AuthenticatedMasterRoute: typeof AuthenticatedMasterRouteWithChildren
  AuthenticatedOperacionalRoute: typeof AuthenticatedOperacionalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedCheckInRoute: AuthenticatedCheckInRouteWithChildren,
  AuthenticatedGiroSalaRoute: AuthenticatedGiroSalaRouteWithChildren,
  AuthenticatedHospitalRoute: AuthenticatedHospitalRouteWithChildren,
  AuthenticatedMasterRoute: AuthenticatedMasterRouteWithChildren,
  AuthenticatedOperacionalRoute: AuthenticatedOperacionalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EntrarRoute: EntrarRoute,
  ConviteTokenRoute: ConviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
